version: '3.8'

services:
    web-service:
      image: devopsdockeruh/simple-web-service
      build: .
      #volumes:
      #  - ./logs.txt:/usr/src/app/text.log
      container_name: web-202
      command: server

      ports:
            - "8080:8080"