version: '3.8'

services:
    front203:
      image: front14
      ports:
        - 5000:5000

    back203:
      image: back14
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST = redis


    redis:
      image: redis:6-alpine
      restart: unless-stopped
      # no ports!
