version: '3.8'

services:
  front303:
    image: front34
    build: "${MATERIAL_APPLICATIONS}/example-frontend"
    # ports:
    #   - 5000:5000

  back303:
    image: back34
    build: "${MATERIAL_APPLICATIONS}/example-backend"
    # ports:
    #   - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://127.0.0.1
      #- REQUEST_ORIGIN=http://localhost/
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_pgsql
    volumes:
      - ./database/pg:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 8080:8080



